### PR TITLE
Remove old Dockerfile and update README instructions

### PR DESCRIPTION
**Pull request by partytax**
Brad confirmed Dockerfile is no longer relevant, so I deleted it.

Added some dependencies that I discovered when running the app for the first time, and put dependencies in a bullet list form.

Added note about exact name of some system packages necessary on Debian/Ubuntu systems.

Removed reference to parking_reform.R file that doesn't exist.

Removed reference to App.R file that doesn't exist, and replaced with two-liner for running app locally.

### CODE REVIEW

**Comment by bradbakermusic** [comment]
lgtm!

**Comment by bradbakermusic** [comment]
Not that I can think of with this PR. Have you talked to Tony about other feature requests? I think he has some ideas for things he'd like to see updated.

**Comment by partytax** [comment]
Might also retry the whole process of running and deploying the app on MacOS/Windows too, so I can update setup steps for that.

**Comment by bradbakermusic** [comment]
dope! sounds like a good idea

**Comment by partytax** [comment]
Hey. Would you mind merging so folks have the most up-to-date info on how to build the project? Thanks in advance!

**Pull request merged**
