### PR TITLE
Drop selection

### PR DESCRIPTION
**Pull request by devinmacarthur**
Here I have changed the inputs to drop-downs, removed opacity, and renamed the csv file.

### CODE REVIEW

**Comment by bradbakermusic** [comment]
this is great, @devinmacarthur! Just switch the `Vari...` stuff then we can merge it.

**Comment by devinmacarthur** [comment]
> this is great, @devinmacarthur! Just switch the `Vari...` stuff then we can merge it.

what is the Vari... stuff and how do I switch it?

**Comment by bradbakermusic** [comment]
It's the stuff I mentioned in the inline comments. It's just that verification got misspelled as varification on lines 57, 58, and 61 of the ui.R file

**Comment by bradbakermusic** [comment]
Dope! Merging!

**Pull request merged**
